//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServicioTarjetasULACIT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TARJETAS_SW_ULACITEntities : DbContext
    {
        public TARJETAS_SW_ULACITEntities()
            : base("name=TARJETAS_SW_ULACITEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Emisor> Emisor { get; set; }
        public virtual DbSet<Tarjeta> Tarjeta { get; set; }
    }
}
